spring:
  application:
    name: pets-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      connect-timeout: 5000
      response-timeout: 15000

management:
  endpoints:
    web:
      exposure:
        include: "*"
