#Spring Boot Port
server:
  # port: 8001  #no need to set port for GCP App Engine, it runs on 8080 and is adequate for the app
  # servlet:
    # context-path: /pets-gateway
  # There’s no concept of context path in WebFlux so there’s no equivalent property

routes_base_url:
  pets_service: 'https://pets-service.appspot.com'
  pets_database: 'https://pets-database.appspot.com'
  pets_authenticate: 'https://pets-authenticate.appspot.com'
