#Spring Boot Port
server:
  port: 8001
  # servlet:
    # context-path: /pets-gateway
    # There’s no concept of context path in WebFlux so there’s no equivalent property

routes_base_url:
  pets_database: 'http://pets-database:8002'
  pets_service: 'http://pets-service:8003'
  pets_authenticate: 'http://pets-authenticate:8004'
